
package com.pst.test.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.0
 * Mon Jun 01 13:43:14 EDT 2015
 * Generated source version: 3.1.0
 */

@XmlRootElement(name = "fetchSpecificPersonMessage", namespace = "http://service.test.pst.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fetchSpecificPersonMessage", namespace = "http://service.test.pst.com/")

public class FetchSpecificPersonMessage {

    @XmlElement(name = "personName")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

